### ISSUE TITLE
Check for `release/v1.0.0` style tags

### ISSUE THREAD

**Issue by jfelchner** [elidupuis/ember-cli-build-info#12]
It seems that build info can only find strictly version tags like `v1.23.4`.  We tag our releases with a `release/` prefix so that in Git GUIs they show up in a folder.

It would be nice if build info could look those up as well.

**Comment by elidupuis** [comment]
I don't really use Git GUIs but that does sound interesting.

I opted for an external semver parser (https://github.com/coolaj86/semver-utils#semverutilsparsesemverstring) a while ago but that only deals with the actual semver, not any prefix.

I'm open to PRs and suggestions :wink:

**Comment by elidupuis** [comment]
For reference, these are the parts concerning the version parsing:
- https://github.com/elidupuis/ember-cli-build-info/blob/master/index.js#L23
- https://github.com/elidupuis/ember-cli-build-info/blob/master/lib/parse-version.js
