### ISSUE TITLE
Update Ember CLI

### ISSUE THREAD

**Issue by elidupuis** [elidupuis/ember-cli-build-info#3]

**Comment by spruce** [comment]
For upgrading to ember 2.x integrate the following commit: https://github.com/James1x0/ember-cli-build-info/commit/93b14c6b5c8adece34711d2e7baf9ae2d8f96dc9

**Comment by elidupuis** [comment]
Yes, but if also like to bring this addon up to date with Ember CLI version (currently 1.13.14 as of).
